export const SETUSERINFO = 'SETUSERINFO'
export const SETUSER = 'SETUSER'
export const SETORDERDATA = 'SETORDERDATA'
export const CLOSECONTENT = 'CLOSECONTENT'
export const OPENCONTENT = 'OPENCONTENT'
export const CLOSEALERT = 'CLOSEALERT'
export const OPENALERT = 'OPENALERT'
export const ClOSESWIPER = 'ClOSESWIPER'
export const OPENSWIPER = 'OPENSWIPER'
export const SETADDRESSDATA = 'SETADDRESSDATA'
export const CLOSEGOODS = 'CLOSEGOODS' //关闭购物窗口
export const OPENGOODS = 'OPENGOODS' //打开购物窗口
export const SETGOODSDATA = 'SETGOODSDATA' //重置当前可购买的商品的信息
export const SETFORMDATA = 'SETFORMDATA' //设置当前显示在地址编辑页的表单数据
export const SETDEFAULTADDRESS = 'SETDEFAULTADDRESS' //设置默认的地址
export const SETDISCUSSDATA = 'SETDISCUSSDATA' //设置默认的地址
export const OPENPOP = 'OPENPOP'
export const CLOSEPOP = 'CLOSEPOP'
export const OPENSPINNER = 'OPENSPINNER'
export const CLOSESPINNER = 'CLOSESPINNER'
export const SETBOOKDATA = 'SETBOOKDATA'
export const OPENBILL = 'OPENBILL'
export const CLOSEBILL = 'CLOSEBILL'
export const SETCANLOAD = 'SETCANLOAD'
